//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerAPI.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Project_Id { get; set; }
        public string Project_Name { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public int Priority { get; set; }
        public bool Is_Active { get; set; }
    }
}
